version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: node-js-server:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8080"
    networks:
      - webnet
networks:
  webnet:

